# NumPy Assignment

In [1]:
import numpy as np

In [2]:
# 1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
intArr = np.arange(100,200,10)
intArr = intArr.reshape(5,2)
print("Integer array:-\n",intArr)

Integer array:-
 [[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [3]:
# 2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values.

arbArr = np.random.random((3,3,3))
print("3x3x3 array with arbitrary values:-\n\n",arbArr)
print("\nMinimum value in the array is ",arbArr.min())
print("\nMaximum value in the array is ",arbArr.max())

3x3x3 array with arbitrary values:-

 [[[0.82405545 0.40575495 0.92048298]
  [0.66969597 0.53290651 0.87414202]
  [0.6965636  0.57060216 0.84834688]]

 [[0.1544895  0.9940541  0.47263727]
  [0.43668085 0.8902515  0.49938043]
  [0.44004335 0.21580356 0.48245227]]

 [[0.59192875 0.79665569 0.7800534 ]
  [0.86846257 0.99113359 0.91901164]
  [0.18089987 0.43886664 0.40551119]]]

Minimum value in the array is  0.1544895031239687

Maximum value in the array is  0.9940541032710046


In [4]:
# 3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

diagArr = np.diag([1,2,3,4,5])
print("The zero matrix with diagonal elements as 1, 2, 3, 4, 5 is:-\n\n", diagArr)

The zero matrix with diagonal elements as 1, 2, 3, 4, 5 is:-

 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [5]:
# 4. Given an array, arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# i) Extract all odd numbers from arr
# ii) Replace all odd numbers in arr with -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Initial array:-\n\n",arr)
print("\nOdd numbers in the array are:\n")
for i in arr:
    if(i%2 == 1):
        print(i)
        arr[i] = -1
print("\nNew array after replacing odd numbers with -1:-\n\n",arr)

Initial array:-

 [0 1 2 3 4 5 6 7 8 9]

Odd numbers in the array are:

1
3
5
7
9

New array after replacing odd numbers with -1:-

 [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
# 5.Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

eyeArr = np.eye(3,3)
print("3x3 identity matrix with 1 as diagonal elements:-\n",eyeArr)

3x3 identity matrix with 1 as diagonal elements:-
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# 6. Write a NumPy program to convert an array to a float type.

convArr = np.random.randint(0,10,(2,3))
print("Integer array:-\n",convArr)
print("\nArray after converting to float:-\n",convArr.astype(np.float))

Integer array:-
 [[9 7 0]
 [7 6 6]]

Array after converting to float:-
 [[9. 7. 0.]
 [7. 6. 6.]]


In [8]:
# 7. Write a NumPy program to generate five random numbers from the normal distribution.

randArr = np.random.normal(1,10,5)
print("Five random numbers from the normal distribution:-\n", randArr)

Five random numbers from the normal distribution:-
 [ -1.78269392   4.21740221   6.67648344   9.55793188 -11.18990251]


In [9]:
# 8. Following is the input NumPy array delete column two and insert following new column in its place.
# sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
# newColumn = numpy.array([[10,10,10]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print("Initial Array:-\n",sampleArray)
sampleArray[:,1] = newColumn
print("\nArray after changing the 2nd column:-\n",sampleArray)

Initial Array:-
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

Array after changing the 2nd column:-
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


In [10]:
# 9. Write a NumPy program to compute the multiplication of two given matrices.

# Method 1
matrix1 = np.array(([1,2,3],[1,3,5]))
matrix2 = np.array(([4,5,6],[3,8,2]))
print('Matrix 1:\n',matrix1)
print('\nMatrix 2:\n',matrix2)
matrix3 = matrix1 * matrix2
print('\n\nProduct of the two matrices, Matrix 3:\n',matrix3)

Matrix 1:
 [[1 2 3]
 [1 3 5]]

Matrix 2:
 [[4 5 6]
 [3 8 2]]


Product of the two matrices, Matrix 3:
 [[ 4 10 18]
 [ 3 24 10]]


In [11]:
# Method 2

matrix1 = np.array(([1,2,3],[1,3,5]))
matrix2 = np.array(([4,5,6],[3,8,2]))
print('Matrix 1:\n',matrix1)
print('\nMatrix 2:\n',matrix2)
matrix3 = np.multiply(matrix1,matrix2)
print('\n\nProduct of the two matrices, Matrix 3:\n',matrix3)

Matrix 1:
 [[1 2 3]
 [1 3 5]]

Matrix 2:
 [[4 5 6]
 [3 8 2]]


Product of the two matrices, Matrix 3:
 [[ 4 10 18]
 [ 3 24 10]]


In [12]:
# 10. Write a NumPy program to create a random vector of size 10 and sort it.

randVect = np.random.random(10)
print("Random vector values are:-\n", randVect)
randVect.sort()
print("\n\nSorted random vector values are:-\n", randVect)

Random vector values are:-
 [0.68735085 0.88948755 0.64793927 0.14827097 0.53492146 0.74356372
 0.77353994 0.95166688 0.32368796 0.99846595]


Sorted random vector values are:-
 [0.14827097 0.32368796 0.53492146 0.64793927 0.68735085 0.74356372
 0.77353994 0.88948755 0.95166688 0.99846595]


In [13]:
# 11. Write a NumPy program to compute the covariance matrix of two arrays.

arr1 = np.array(([1,2,3],[1,3,5]))
arr2 = np.array(([4,5,6],[3,8,2]))
print('Matrix 1:\n',arr1)
print('\nMatrix 2:\n',arr2)
covArr = np.cov(arr1,arr2)
print('\n\nCovariance of the two matrices:\n',covArr)

Matrix 1:
 [[1 2 3]
 [1 3 5]]

Matrix 2:
 [[4 5 6]
 [3 8 2]]


Covariance of the two matrices:
 [[ 1.          2.          1.         -0.5       ]
 [ 2.          4.          2.         -1.        ]
 [ 1.          2.          1.         -0.5       ]
 [-0.5        -1.         -0.5        10.33333333]]


In [14]:
# 12.Create a 4X2 integer array and Prints its :
# i) The shape of an array.
# ii) Array dimensions.
# iii) The Length of each element of the array in bytes

intArr = np.random.random((4,2))
print("Shape of the array is ",intArr.shape)
print("Dimension of the array is ",intArr.ndim)
print("Length of each element in bytes is ",intArr.itemsize)

Shape of the array is  (4, 2)
Dimension of the array is  2
Length of each element in bytes is  8


In [15]:
# 13. Write a NumPy program to concatenate element-wise two arrays of string.

arrNm1 = np.array(['Leeba','Laila'])
arrNm2 = np.array(['Mohamed','Basheer'])
print("Arrays before concatenation\n",arrNm1,"\n",arrNm2)
concatArr = np.char.add(arrNm1,arrNm2)
print("\n\nArray after the concatenation",concatArr)

Arrays before concatenation
 ['Leeba' 'Laila'] 
 ['Mohamed' 'Basheer']


Array after the concatenation ['LeebaMohamed' 'LailaBasheer']


In [19]:
# 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the 
# elements of a given array.

charArr = np.array(['LeeBa', 'laiLa', 'UMer'])
print("Initial array:-\n", charArr)
print("\n\nArray after applying capitalize():-\n", np.char.capitalize(charArr))
print("\n\nArray after applying lower():-\n", np.char.lower(charArr))
print("\n\nArray after applying upper():-\n", np.char.upper(charArr))
print("\n\nArray after applying swapcase():-\n", np.char.swapcase(charArr))
print("\n\nArray after applying title():-\n", np.char.title(charArr))

Initial array:-
 ['LeeBa' 'laiLa' 'UMer']


Array after applying capitalize():-
 ['Leeba' 'Laila' 'Umer']


Array after applying lower():-
 ['leeba' 'laila' 'umer']


Array after applying upper():-
 ['LEEBA' 'LAILA' 'UMER']


Array after applying swapcase():-
 ['lEEbA' 'LAIlA' 'umER']


Array after applying title():-
 ['Leeba' 'Laila' 'Umer']


In [22]:
# 15. Write a NumPy program to convert a given array into a list.

listArr = np.array(['AI', 'ML', 'DL', 'NLP', 'CV'])
print("Datatype before type conversion: ",type(listArr))
newListArr = list(listArr)
print("\nDatatype after type conversion: ",type(newListArr))

Datatype before type conversion:  <class 'numpy.ndarray'>

Datatype after type conversion:  <class 'list'>


In [23]:
# 16. Write a NumPy program to compute the sum of all elements, sum of each column and sum of each row of a given array.

# Method 1

sumArr = np.array([[3,3,7],[2,2,2],[5,4,6]])
print("Initial array:-\n", sumArr)
print("\n\nSum of all elements in the array: ", np.sum(sumArr))
print("\n\nSum of all column elements in the array: ", np.sum(sumArr, axis = 0))
print("\n\nSum of all row elements in the array: ", np.sum(sumArr, axis = 1))

Initial array:-
 [[3 3 7]
 [2 2 2]
 [5 4 6]]


Sum of all elements in the array:  34


Sum of all column elements in the array:  [10  9 15]


Sum of all row elements in the array:  [13  6 15]


In [25]:
# Method 2

print("Initial array\n",sumArr)
print("\nSum of all elements",np.sum(sumArr))
print("\nSum of elements in column 1: ",np.sum(sumArr[:,0]))
print("\nSum of elements in column 2: ",np.sum(sumArr[:,1]))
print("\nSum of elements in column 3: ",np.sum(sumArr[:,2]))
print("\nSum of elements in row 1: ",np.sum(sumArr[0,:]))
print("\nSum of elements in row 2: ",np.sum(sumArr[1,:]))
print("\nSum of elements in row 3: ",np.sum(sumArr[2,:]))

Initial array
 [[3 3 7]
 [2 2 2]
 [5 4 6]]

Sum of all elements 34

Sum of elements in column 1:  10

Sum of elements in column 2:  9

Sum of elements in column 3:  15

Sum of elements in row 1:  13

Sum of elements in row 2:  6

Sum of elements in row 3:  15


In [32]:
# 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store
# them into a variable.

tenRowArr = np.random.rand(10,4)
print("10x4 Random array:-\n\n", tenRowArr)
fiveRowArr = tenRowArr[:5]
print("\n\nFirst five rows from the random array:-\n\n", fiveRowArr)

10x4 Random array:-

 [[0.48961193 0.66224381 0.89246389 0.64053607]
 [0.78776028 0.8052944  0.80038466 0.6848905 ]
 [0.1090448  0.8820931  0.19122114 0.06209169]
 [0.89080675 0.76947843 0.52117819 0.3026521 ]
 [0.69642219 0.53287247 0.11495661 0.93909968]
 [0.34220983 0.48867441 0.04657498 0.8807319 ]
 [0.07128389 0.49510246 0.38001291 0.08737501]
 [0.7024428  0.45050023 0.74860284 0.52366221]
 [0.1406233  0.68481845 0.5669359  0.64884562]
 [0.07538538 0.05798774 0.94023867 0.88550436]]


First five rows from the random array:-

 [[0.48961193 0.66224381 0.89246389 0.64053607]
 [0.78776028 0.8052944  0.80038466 0.6848905 ]
 [0.1090448  0.8820931  0.19122114 0.06209169]
 [0.89080675 0.76947843 0.52117819 0.3026521 ]
 [0.69642219 0.53287247 0.11495661 0.93909968]]


In [36]:
# 18. Write a NumPy program to get the unique elements of a 1D and 2D array.

oneDArr = np.array([7,0,3,0,2,4,7,1,8,1,3,5,6,9])
twoDArr = np.array([[34,43,73],[82,22,12],[73,43,22]])
print("1D array: ", oneDArr)
print("\nUnique elements in the 1D array are ", np.unique(oneDArr))
print("\n\n2D array: \n", twoDArr)
print("\nUnique elements in the 2D array are ", np.unique(twoDArr))

1D array:  [7 0 3 0 2 4 7 1 8 1 3 5 6 9]

Unique elements in the 1D array are  [0 1 2 3 4 5 6 7 8 9]


2D array: 
 [[34 43 73]
 [82 22 12]
 [73 43 22]]

Unique elements in the 2D array are  [12 22 34 43 73 82]


In [38]:
# 19. Write a NumPy program to get the unique elements of an array.
# arr= [ -10 12.12 -0.2]

arr = np.array([ -10, 12.12, -0.2])
print("Initial array: ", arr)
print("\nArray with unique elements: ", np.unique(arr))

Initial array:  [-10.    12.12  -0.2 ]

Array with unique elements:  [-10.    -0.2   12.12]


In [44]:
# 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using 
# numpy library .

fileArr = np.random.rand(3,3)
print("Random array created:-\n\n", fileArr)
np.savetxt("NumpyAssignmentText.txt", fileArr)
print("\nArray stored in NumpyAssignmentText.txt")
loadedArr = np.loadtxt("NumpyAssignmentText.txt")
print("\n\nRetrieved array from NumpyAssignmentText.txt:-\n\n", loadedArr)

Random array created:-

 [[0.695819   0.05428215 0.45745562]
 [0.96919031 0.23918856 0.2599421 ]
 [0.27456973 0.09968849 0.9884188 ]]

Array stored in NumpyAssignmentText.txt


Retrieved array from NumpyAssignmentText.txt:-

 [[0.695819   0.05428215 0.45745562]
 [0.96919031 0.23918856 0.2599421 ]
 [0.27456973 0.09968849 0.9884188 ]]
